### ISSUE TITLE
Permission page error

### ISSUE THREAD

**Issue by sayedahmadnawid** [jeremykenedy/laravel-spa#188]
Everything is working fine, except the PERMISSION page. when I visit this page, I confront with following error and the application is crashed. 

runtime-core.esm-bundler.js:1092 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (runtime-core.esm-bundler.js:1092:29)
    at updateComponent (runtime-core.esm-bundler.js:5549:13)
    at processComponent (runtime-core.esm-bundler.js:5503:13)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at patchBlockChildren (runtime-core.esm-bundler.js:5406:13)
    at patchElement (runtime-core.esm-bundler.js:5314:13)
    at processElement (runtime-core.esm-bundler.js:5181:13)
    at patch (runtime-core.esm-bundler.js:5098:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5711:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)

**Comment by jeremykenedynv5** [comment]
I am unable to replicate, make sure the permissions are seeded

**Comment by jeremykenedynv5** [comment]
It is probably returning no permission, check the https request in the console to see what it returns.

**Comment by sayedahmadnawid** [comment]
I am really sorry for reaching you after closing this issue. After solving the above issue, now I am facing another issue where I coulding fix this. I attached the console error message. Could you please help me in this regard. 
![Uploading Screen Shot 2023-02-11 at 18.17.02.png…]()

**Comment by jeremykenedy** [comment]
I don't know the error. The screenshot didn't upload.

**Comment by jeremykenedy** [comment]
Can you post the stack trace or the console error log. Thanks

**Comment by sayedahmadnawid** [comment]
<img width="1315" alt="Screen Shot 2023-02-11 at 18 17 02" src="https://user-images.githubusercontent.com/12025673/218295177-2576e8db-6d64-49ff-bc48-80334a308e8d.png">
Thank you very much, this is the screenshot.

**Comment by jeremykenedy** [comment]
The cafe token has to come from the site matching in your .env APP_URL

**Comment by jeremykenedy** [comment]
This is the line in the config:

https://github.com/jeremykenedy/laravel-spa/blob/released/config/sanctum.php#L18

**Comment by jeremykenedy** [comment]
Alternatively you can set SANCTUM_STATEFUL_DOMAINS

**Comment by jeremykenedy** [comment]
Google 'laraval sanctum csfr token error'

**Comment by sayedahmadnawid** [comment]
I opened the file, should I bring any specific changes? this is my .env file. 
<img width="1315" alt="Screen Shot 2023-02-12 at 14 54 02" src="https://user-images.githubusercontent.com/12025673/218295370-a401e6c1-fe67-40d1-b58c-7ee07ffb4932.png">

**Comment by sayedahmadnawid** [comment]
> Alternatively you can set SANCTUM_STATEFUL_DOMAINS

How I can setup, I am sorry, I am note advanced skilled in laravel and vue.

**Comment by sayedahmadnawid** [comment]
Thank you very much it is fixed.

**Comment by jalilhadjhabib** [comment]
> I am really sorry for reaching you after closing this issue. After solving the above issue, now I am facing another issue where I coulding fix this. I attached the console error message. Could you please help me in this regard.
Uploading Screen Shot 2023-02-11 at 18.17.02.png…


how did you fix it please im facing the same problem

**Comment by jeremykenedy** [comment]
Run the seeders
