### ISSUE TITLE
/admin/permissions doesn't seem to be working

### ISSUE THREAD

**Issue by moipap** [jeremykenedy/laravel-spa#202]
Hey, I've just tried this project and, while logged in as a superadmin,  the permissions page doesn't seem to be working. 

Here's what I get in the console:
Here's what I get: [Vue warn]: Unhandled error during execution of created hook 
  at <RLClientTable data= (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] columns= (9) ['id', 'name', 'slug', 'description', 'roles', 'users', 'created_at', 'updated_at', 'actions'] name=undefined  ... > 
  at <VtClientTable ref="permissionsTable" key=432877 data= (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]  ... > 
  at <Permissions onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {popToast: ƒ, perPageChanged: ƒ, getRoles: ƒ, getPermissions: ƒ, …} > > 
  at <RouterView> 
  at <AdminLayout class="" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade" mode="out-in" > 
  at <RouterView class="" > 
  at <App>

[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RLClientTable data= (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] columns= (9) ['id', 'name', 'slug', 'description', 'roles', 'users', 'created_at', 'updated_at', 'actions'] name=undefined  ... > 
  at <VtClientTable ref="permissionsTable" key=432877 data= (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]  ... > 
  at <Permissions onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {popToast: ƒ, perPageChanged: ƒ, getRoles: ƒ, getPermissions: ƒ, …} > > 
  at <RouterView> 
  at <AdminLayout class="" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade" mode="out-in" > 
  at <RouterView class="" > 
  at <App>

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at module.exports (init-query.js:7:46)
    at Proxy.created (v-client-table.js:91:27)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:36)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at callHook (runtime-core.esm-bundler.js:3590:5)
    at applyOptions (runtime-core.esm-bundler.js:3492:9)
    at finishComponentSetup (runtime-core.esm-bundler.js:7368:9)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7279:9)
    at setupComponent (runtime-core.esm-bundler.js:7201:11)
    at mountComponent (runtime-core.esm-bundler.js:5524:13)

**Comment by moipap** [comment]
the backend seems to be working fine as I get a response from the server: http://127.0.0.1:8000/api/permissions-paginated?page=undefined&per=25, maybe page should be defined, this is what the front end is sending though

**Comment by jeremykenedy** [comment]
I can't replicate it

**Comment by jeremykenedy** [comment]
![Uploading IMG_5896.png…]()
