### ISSUE TITLE
Error into permissions view

### ISSUE THREAD

**Issue by jdosorio** [jeremykenedy/laravel-spa#260]
Error when open view permissions. 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at module.exports (init-query.js:7:46)
    at Proxy.created (v-client-table.js:91:27)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:36)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at callHook (runtime-core.esm-bundler.js:3608:5)
    at applyOptions (runtime-core.esm-bundler.js:3510:9)
    at finishComponentSetup (runtime-core.esm-bundler.js:7387:9)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7298:9)
    at setupComponent (runtime-core.esm-bundler.js:7220:11)
    at mountComponent (runtime-core.esm-bundler.js:5542:13)

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (runtime-core.esm-bundler.js:1108:29)
    at updateComponent (runtime-core.esm-bundler.js:5567:13)
    at processComponent (runtime-core.esm-bundler.js:5521:13)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at patchBlockChildren (runtime-core.esm-bundler.js:5424:13)
    at patchElement (runtime-core.esm-bundler.js:5332:13)
    at processElement (runtime-core.esm-bundler.js:5199:13)
    at patch (runtime-core.esm-bundler.js:5116:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5729:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)

Dont load the table and crash the frontend. Thanks to helpme
![Captura de pantalla 2023-06-07 a la(s) 5 25 13 p m](https://github.com/jeremykenedy/laravel-spa/assets/11360510/1b6a8372-8155-4131-a13b-19e4ecd2be12)

**Comment by jeremykenedy** [comment]
Need to weed it
