### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by bol-nik** [jeremykenedy/laravel-spa#67]
Hello, I did everything according to the instructions, but when I run npm run dev, I get this error

```
failed to load config from /SCRIPTS/laravel-spa/vite.config.ts
error when starting dev server:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:583:10)
    at Object.readFileSync (node:fs:459:35)
    at vite_config_default (/SCRIPTS/laravel-spa/vite.config.ts:103:17)
    at loadConfigFromFile (file:///SCRIPTS/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62960:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///SCRIPTS/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62575:28)
    at async createServer (file:///SCRIPTS/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:61883:20)
    at async CAC.<anonymous> (file:///SCRIPTS/laravel-spa/node_modules/vite/dist/node/cli.js:730:24)
```

My software:
ubuntu server 22.04.1
mysql (version 8.0.31)
php8.1
nodejs (version 19.2.0)
npm (version 9.2.0)

Please help me figure this out

**Comment by jeremykenedy** [comment]
You are missing env variables from the process env

**Comment by bol-nik** [comment]
> * You do not have the PATH set in bash or zsh.
> * Possible issue with one of the vite js configs (e.g. `tsconfig.json`) based on your setup.
> * You are missing env variables from the process env.
> * I think it has something to do with your environment, I am unable to replicate the issue.
> * There is an issue with the package npm path. It seems that `import path from 'path';` package used fails to around here:

Thank you very much for the quick response

**Comment by jeremykenedy** [comment]
Did you get it?

**Comment by bol-nik** [comment]
On Ubuntu, I was unable to run the project.
On Windows, I downloaded XAMP, followed the instructions, installed
PHP 8.1.12
node8.19.2
npm v18.12.1
I run npm run dev and I also get the same error

`failed to load config from D:\php\laravel-spa\laravel-spa\vite.config.ts
error when starting dev server:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:592:10)
    at Object.readFileSync (node:fs:468:35)
    at vite_config_default (D:\php\laravel-spa\laravel-spa\vite.config.ts:103:17)
    at loadConfigFromFile (file:///D:/php/laravel-spa/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62960:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///D:/php/laravel-spa/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62575:28)
    at async createServer (file:///D:/php/laravel-spa/laravel-spa/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:61883:20)
    at async CAC.<anonymous> (file:///D:/php/laravel-spa/laravel-spa/node_modules/vite/dist/node/cli.js:730:24)`

**Comment by jeremykenedy** [comment]
See Step 3: https://danielkon.medium.com/fix-typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-7e659668d953

**Comment by bol-nik** [comment]
Nothing helps, as I understand it, many people have this problem, not only me

Here is another example:
import path from 'path';
let path1 = path.resolve(__dirname, 'node_modules');
console log(path1);

Shows:
D:\php\laravel-spa\laravel-spa\node_modules

That is, the path.resolve() method works
